### ISSUE TITLE
Works with 4x ?

### ISSUE THREAD

**Issue by lpj145** [CakeDC/cakephp-roadrunner#1]
I'm see this plugin now, and, trying to understand how he can improve my application.

Thanks for job.

**Comment by steinkel** [comment]
Hi @lpj145 after some benchmarks I decided to keep going with https://github.com/CakeDC/cakephp-phppm as it provides similar performance with the added value of keeping all the project within the php boundaries. Take a look at https://github.com/CakeDC/cakephp-phppm/tree/cake4
